### ISSUE TITLE
utp doesn't have gracious connection closing

### ISSUE THREAD

**Issue by dignifiedquire** [libp2p/js-libp2p-utp#19]
It seems the utp module is broken, so CI fails

**Comment by daviddias** [comment]
libutp doesn't implement the FIN flag, unfortunately, which makes thing fail.

**Comment by daviddias** [comment]
Work happening at https://github.com/libp2p/js-libp2p-utp/pull/74

**Comment by daviddias** [comment]
**Crux** continues to exist https://github.com/libp2p/js-libp2p-utp/pull/74/files#r169038393

**Comment by daviddias** [comment]
@mafintosh signaled that this situation has changed! https://github.com/bittorrent/libutp/commit/04cee45bb7684c53607b0ed4ac855413fc0bf2e3 Thanks for keeping tabs on it! 

Full PR here https://github.com/bittorrent/libutp/pull/102

**Comment by daviddias** [comment]
`utp-native` now has this feature too 🎉🎉🎉

https://github.com/mafintosh/utp-native/issues/5#issuecomment-435567736

Thaaaaank you @mafintosh ❤️❤️❤️

**Comment by daviddias** [comment]
It is all happening on https://github.com/libp2p/js-libp2p-utp/pull/80, soon on a libp2p bundle close to you™
